runtime: python27
api_version: 1
threadsafe: true

# default_expiration: "30d"

handlers:
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: site/\1
  upload: site/(.*\.(appcache|manifest))
  expiration: "0m"
  secure: always

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: site/\1
  upload: site/(.*\.atom)
  # expiration: "1h"
  secure: always

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: site/\1
  upload: site/(.*\.crx)
  secure: always

- url: /(.*\.css)
  mime_type: text/css
  static_files: site/\1
  upload: site/(.*\.css)
  secure: always

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: site/\1
  upload: site/(.*\.eot)
  secure: always

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: site/\1
  upload: site/(.*\.htc)
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: site/\1
  upload: site/(.*\.html)
  # expiration: "1h"
  secure: always

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: site/\1
  upload: site/(.*\.ico)
  # expiration: "7d"
  secure: always

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: site/\1
  upload: site/(.*\.js)
  secure: always

- url: /(.*\.json)
  mime_type: application/json
  static_files: site/\1
  upload: site/(.*\.json)
  # expiration: "1h"
  secure: always

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: site/\1
  upload: site/(.*\.m4v)
  secure: always

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: site/\1
  upload: site/(.*\.mp4)
  secure: always

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: site/\1
  upload: site/(.*\.(ogg|oga))
  secure: always

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: site/\1
  upload: site/(.*\.ogv)
  secure: always

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: site/\1
  upload: site/(.*\.otf)
  secure: always

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: site/\1
  upload: site/(.*\.rss)
  # expiration: "1h"
  secure: always

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: site/\1
  upload: site/(.*\.safariextz)
  secure: always

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: site/\1
  upload: site/(.*\.(svg|svgz))
  secure: always

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: site/\1
  upload: site/(.*\.swf)
  secure: always

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: site/\1
  upload: site/(.*\.ttf)
  secure: always

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: site/\1
  upload: site/(.*\.txt)
  secure: always

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: site/\1
  upload: site/(.*\.unity3d)
  secure: always

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: site/\1
  upload: site/(.*\.webm)
  secure: always

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: site/\1
  upload: site/(.*\.webp)
  secure: always

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: site/\1
  upload: site/(.*\.woff)
  secure: always

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: site/\1
  upload: site/(.*\.xml)
  # expiration: "1h"
  secure: always

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: site/\1
  upload: site/(.*\.xpi)
  secure: always

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: site/\1
  upload: site/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  secure: always

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: site/\1
  upload: site/(.*\.(mid|midi|mp3|wav))  
  secure: always

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: site/\1
  upload: site/(.*\.(doc|exe|ppt|rtf|xls))
  secure: always

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: site/\1
  upload: site/(.*\.(bz2|gz|rar|tar|tgz|zip))
  secure: always

# index files
- url: /(.+)/
  static_files: site/\1/index.html
  upload: site/(.+)/index.html
  # expiration: "15m"
  secure: always

- url: /(.+)
  static_files: site/\1/index.html
  upload: site/(.+)/index.html
  # expiration: "15m"
  secure: always

# site root
- url: /
  static_files: site/index.html
  upload: site/index.html
  expiration: "1m"
  secure: always
